version: '3.8'

volumes:
  mysql_auth:
    name: auth_service_vol
    driver: local
  mongo_chat:
    name: chat_messages_service_vol
    driver: local
  mysql_chat:
    name: chat_service_vol
    driver: local
  rabbitmq:
    name: rabbitmq_vol
    driver: local

services:
  auth_db:
    container_name: auth_service_mysql
    image: library/mysql:8.0.22
    environment:
      MYSQL_DATABASE: auth_service_database
      MYSQL_USER: ${AUTH_SERVICE_MYSQL_USER}
      MYSQL_PASSWORD: ${AUTH_SERVICE_MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${AUTH_SERVICE_MYSQL_ROOT_PASS}
    ports:
      - 3306:3306
    volumes:
      - mysql_auth:/var/lib/mysql
  messages_db:
    container_name: chat_messages_service_mongo
    image: library/mongo:latest
    environment:
      MONGO_INITDB_DATABASE: chat_messages_service_database
      MONGO_INITDB_ROOT_USERNAME: ${CHAT_MESSAGES_SERVICE_ROOT_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CHAT_MESSAGES_SERVICE_ROOT_MONGO_PASS}
    ports:
      - 27017:27017
    volumes:
      - mongo_chat:/var/lib/mongo
      - ./init-chat-messages-service-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  chat_db:
    container_name: chat_service_mysql
    image: library/mysql:8.0.22
    environment:
      MYSQL_DATABASE: chat_service_database
      MYSQL_USER: ${CHAT_SERVICE_MYSQL_USER}
      MYSQL_PASSWORD: ${CHAT_SERVICE_MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${CHAT_SERVICE_MYSQL_ROOT_PASS}
    ports:
      - 3307:3306
    volumes:
      - mysql_chat:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    command: sh -c "rabbitmq-plugins enable rabbitmq_stomp; rabbitmq-server"
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - rabbitmq:/etc/rabbitmq/
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq/
  # Mail catcher for local debugging
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025 # smtp port
      - 8025:8025 # web ui port