spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service_database?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: user-service-user
    password: '{cipher}a652ce1c1c31ee4bd4c3a225c2d56f50aaea9ec830643a6e2fe7bddaef2720d88ce9e7e70e4da656423928a18012c39f'
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    pl:
      kubaretip:
        userservice: debug
server:
  port: 10000
  forward-headers-strategy: framework