spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

server:
  forward-headers-strategy: framework