spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: '{cipher}601013fed9943a670115c00b51e50faf1b09f23cbe94a72eaab9d4a559320570'
    password: '{cipher}1b65f200e4cd8eb34cd0b2a0447e84238b63a5b30220e46720d59976d9af0f46'
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    pl:
      kubaretip:
        userservice: debug
server:
  port: 10000
  forward-headers-strategy: framework