spring:
  mail:
    host: 127.0.0.1
    port: 1025
  task:
    execution:
      thread-name-prefix: mail-service-task-
      pool:
        core-size: 2
        max-size: 25
        queue-capacity: 10000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq-user
    password: '{cipher}3adfb46bde0f96695af1853733d8774f0012b158e34b64a1254660f509c65e1b666020c71b435e7a78a36d31c2845cbf'
server:
  port: 9998
mail:
  baseUrl: http://localhost:8762/api