spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_database?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: auth-service-user
    password: '{cipher}e5ea373656b09cb959f93338c5be9fc143ee36d5940ac51e62a724da975bfc864779abc0467de644334060213569fd02'
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    pl:
      kubaretip:
        authservice: debug

server:
  port: 9999
  forward-headers-strategy: framework